wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.13
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1751372291
    t:
      1:
      - 1
      - 41
      - 55
      - 100
      2:
      - 1
      - 41
      - 55
      - 100
      3:
      - 23
      4: 3.11.13
      5: 0.17.0
      8:
      - 4
      - 5
      13: darwin-arm64
epochs:
  desc: null
  value: 5
batch_size:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 0.001
val_percent:
  desc: null
  value: 0.002
save_checkpoint:
  desc: null
  value: true
img_scale:
  desc: null
  value: 0.5
amp:
  desc: null
  value: false
